---
to: internal/server/server.go
---
package server

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/<%= spec.meta.repo.org %>/<%= spec.meta.slug %>/internal/config"
	"github.com/<%= spec.meta.repo.org %>/<%= spec.meta.slug %>/internal/routes"
	// >>> idp:imports
	// <<< idp:imports
)

// New builds the engine without binding a port.
//
// Separated from main's http.Server for the same reason the Node runtime separates buildServer
// from start: tests exercise routes through httptest with no port bound, which keeps the suite
// parallel-safe and free of port collisions.
func New(cfg *config.Config) *gin.Engine {
	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.New()

	// Trust the proxy chain so ClientIP() is the real client from X-Forwarded-For rather than the
	// ingress controller's pod IP. Rate limiting keys off that address, so getting this wrong
	// makes the limiter treat all traffic as coming from a single client. The same posture as
	// uvicorn's forwarded_allow_ips="*" in the Python runtime.
	_ = r.SetTrustedProxies([]string{"0.0.0.0/0", "::/0"})

	// A panic in a handler becomes the shared 500 envelope rather than a dropped connection.
	// The panic value itself is deliberately not echoed to the client — it leaks file paths and
	// internal state — but it is logged with a stack by gin before this function runs.
	r.Use(gin.CustomRecovery(func(c *gin.Context, _ any) {
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{
			"error":      "Internal Server Error",
			"statusCode": http.StatusInternalServerError,
		})
	}))

	r.Use(errorEnvelope(cfg))

	// Middleware order is significant and gin runs these in the order they are added — first
	// added, first to see a request. The generator inserts them in MIDDLEWARE_PRIORITY order,
	// the same effective order as the Node and Python runtimes:
	//
	//     logging → cors → rate limit → validation → auth
	//
	// >>> idp:plugins
	// <<< idp:plugins

	routes.RegisterHealth(r)

	// >>> idp:routes
	// <<< idp:routes

	r.NoRoute(func(c *gin.Context) {
		c.JSON(http.StatusNotFound, gin.H{
			"error":      "Not Found",
			"message":    "Route " + c.Request.Method + " " + c.Request.URL.Path + " not found",
			"statusCode": http.StatusNotFound,
		})
	})

	return r
}

// errorEnvelope converts errors handlers attach via c.Error() into the one failure shape every
// runtime in this portal returns: error, message, statusCode. A client that talks to two services
// generated by this portal must not have to branch on which language each was written in.
func errorEnvelope(cfg *config.Config) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next()

		if len(c.Errors) == 0 || c.Writer.Written() {
			return
		}

		err := c.Errors.Last().Err
		status := c.Writer.Status()
		if status < http.StatusBadRequest {
			status = http.StatusInternalServerError
		}

		// >>> idp:error-cases
		// <<< idp:error-cases

		// Internal messages never cross the boundary in production — they leak file paths,
		// dependency versions and query shapes.
		if status >= http.StatusInternalServerError && cfg.Environment == "production" {
			c.JSON(status, gin.H{"error": "Internal Server Error", "statusCode": status})
			return
		}

		c.JSON(status, gin.H{
			"error":      http.StatusText(status),
			"message":    err.Error(),
			"statusCode": status,
		})
	}
}
