---
to: app/main.py
---
import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Starlette's HTTPException, not FastAPI's — and the difference is a working 404 envelope.
# FastAPI's is a *subclass* of this one, and a route that matches nothing raises the parent
# directly, so a handler registered on the subclass never sees it: unmatched routes fell through
# to the framework default and answered {"detail": "Not Found"} while every handled error used
# the shared envelope. Registering on the parent catches both.
from starlette.exceptions import HTTPException

from app.config import settings
from app.logging_config import configure_logging
from app.routes.health import router as health_router

logger = logging.getLogger("<%= spec.meta.slug %>")


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Startup and shutdown, in one place.

    The yield is the running application. Everything before it runs once at boot; everything after
    runs on SIGTERM, before uvicorn stops accepting connections and after in-flight requests
    finish. That ordering is what makes a rolling update not drop the requests already in progress
    on each terminating pod.
    """
    configure_logging()
    logger.info("starting", extra={"port": settings.PORT, "env": settings.ENVIRONMENT})

    # >>> idp:startup
    # <<< idp:startup

    yield

    # >>> idp:shutdown
    # <<< idp:shutdown

    logger.info("stopped")


def create_app() -> FastAPI:
    """Builds the app without serving it.

    Separated from the uvicorn call in ``app/__main__.py`` for the same reason the Node runtime
    separates ``buildServer`` from ``start``: tests exercise routes through ``TestClient`` with no
    port bound, which keeps the suite parallel-safe and free of port collisions.
    """
    app = FastAPI(
        title="<%= spec.meta.slug %>",
        version="0.1.0",
        lifespan=lifespan,
        # `/docs` and `/openapi.json` are FastAPI's defaults and they are also a CONTRACT: the
        # Service Catalog fetches the document from exactly that path, so moving it removes this
        # service's API documentation from the portal. Stated explicitly rather than left to the
        # default, so the coupling is visible to whoever considers changing it.
        docs_url="/docs",
        openapi_url="/openapi.json",
        # ReDoc off: it renders the same document as /docs, and two consoles is one more route
        # to reason about for no additional information.
        redoc_url=None,
        # >>> idp:app-kwargs
        # <<< idp:app-kwargs
    )

    # Middleware order is significant, and this region is deliberately in REVERSE of it.
    #
    # `add_middleware` inserts at the front of the stack, so the LAST one added is the outermost —
    # the first to see an incoming request. The generator therefore emits these in descending
    # priority, and the resulting request path is:
    #
    #     logging → cors → rate limit → validation → auth
    #
    # which is the same order the Node and Go runtimes process a request in. Every position is
    # load-bearing: logging outermost so everything below it is traced, CORS before auth or
    # preflight OPTIONS (which carry no credentials) get a 401 the browser reports as an opaque
    # CORS failure, and rate limiting before auth so unauthenticated floods are rejected before
    # any token work.
    #
    # Reading bottom-to-top gives you the order a request actually travels.
    # >>> idp:plugins
    # <<< idp:plugins

    app.include_router(health_router)

    # >>> idp:routes
    # <<< idp:routes

    @app.exception_handler(HTTPException)
    async def http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
        """One error envelope, identical to the Node and Go runtimes.

        A client that talks to two services generated by this portal must not have to branch on
        which language each was written in, so the keys here — ``error``, ``message``,
        ``statusCode`` — are contractual rather than incidental.
        """
        logger.error("request failed", extra={"status": exc.status_code, "path": request.url.path})

        # >>> idp:error-cases
        # <<< idp:error-cases

        return JSONResponse(
            status_code=exc.status_code,
            content={
                "error": exc.__class__.__name__,
                "message": exc.detail,
                "statusCode": exc.status_code,
            },
        )

    @app.exception_handler(Exception)
    async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
        logger.exception("unhandled error", extra={"path": request.url.path})

        # Stack traces and internal messages never cross the boundary in production — they leak
        # file paths, dependency versions and query shapes.
        if settings.ENVIRONMENT == "production":
            body = {"error": "Internal Server Error", "statusCode": 500}
        else:
            body = {"error": exc.__class__.__name__, "message": str(exc), "statusCode": 500}

        return JSONResponse(status_code=500, content=body)

    return app


app = create_app()
