---
to: app/pages/index.vue
---
<script setup lang="ts">
/**
 * The landing page.
 *
 * `pages/` is the route table: this file is `/`, and adding `pages/about.vue` adds `/about` with
 * nothing to register. That is what the framework contract means by `routing: 'file-based'`.
 */
const config = useRuntimeConfig();
</script>

<template>
  <main class="page">
    <h1><%= spec.meta.projectName %></h1>
    <p><%= spec.meta.description ?? 'Generated by the Internal Developer Portal.' %></p>

    <p class="hint">
      Edit <code>app/pages/index.vue</code> to change this page. Public runtime configuration is
      available as <code>config.public</code>, currently
      {{ Object.keys(config.public).length }} key(s).
    </p>
  </main>
</template>

<style scoped>
/*
 * Scoped by default in a single-file component: Vue rewrites these selectors so they cannot leak
 * out of this file. It is the same isolation CSS Modules gives, without a naming convention.
 */
.page {
  max-width: 42rem;
  margin: 0 auto;
  padding: 4rem 1.5rem;
  font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;
}
.hint {
  font-size: 0.875rem;
  opacity: 0.7;
}
</style>
