---
to: tests/test_health.py
---
from fastapi.testclient import TestClient

from app.main import create_app


def test_health_reports_ok() -> None:
    """Liveness answers without touching anything downstream.

    Asserted against a client built with no port bound, which is why ``create_app`` is separate
    from the uvicorn call — the suite stays parallel-safe and free of port collisions.
    """
    with TestClient(create_app()) as client:
        response = client.get("/health")

    assert response.status_code == 200
    assert response.json()["status"] == "ok"
    assert response.json()["service"] == "<%= spec.meta.slug %>"


def test_ready_answers_rather_than_hanging() -> None:
    """Readiness must answer — 200 with no failing checks, 503 with one.

    Deliberately not ``== 200``: this same test ships into projects whose ORM recipe registers a
    database check, and in a test run there is no database to reach. What the suite can assert
    everywhere is the shape of the behaviour; whether /ready disagrees with /health under a real
    outage is the smoke harness's job, with a real environment.
    """
    with TestClient(create_app()) as client:
        response = client.get("/ready")

    assert response.status_code in (200, 503)
    body = response.json()
    assert body["status"] in ("ready", "unavailable")
    assert (response.status_code == 200) == (body["status"] == "ready")


def test_unknown_route_uses_the_shared_error_envelope() -> None:
    """404s carry the same keys as every other error, in every runtime.

    A client talking to two services generated by this portal must not have to branch on which
    language each was written in.
    """
    with TestClient(create_app()) as client:
        response = client.get("/does-not-exist")

    assert response.status_code == 404
    body = response.json()
    assert set(body) >= {"error", "message", "statusCode"}
    assert body["statusCode"] == 404
