---
to: tests/test_health.py
---
from fastapi.testclient import TestClient

from app.main import create_app


def test_health_reports_ok() -> None:
    """Liveness answers without touching anything downstream.

    Asserted against a client built with no port bound, which is why ``create_app`` is separate
    from the uvicorn call — the suite stays parallel-safe and free of port collisions.
    """
    with TestClient(create_app()) as client:
        response = client.get("/health")

    assert response.status_code == 200
    assert response.json()["status"] == "ok"
    assert response.json()["service"] == "<%= spec.meta.slug %>"


def test_ready_reports_ready_with_no_checks_registered() -> None:
    """An API with no dependencies is ready as soon as it is up.

    The ``idp:readiness-checks`` region is empty until a recipe that owns a dependency fills it,
    and an empty check set must mean ready rather than unavailable — otherwise a service with no
    database would never join its own Service.
    """
    with TestClient(create_app()) as client:
        response = client.get("/ready")

    assert response.status_code == 200
    assert response.json()["status"] == "ready"


def test_unknown_route_uses_the_shared_error_envelope() -> None:
    """404s carry the same keys as every other error, in every runtime.

    A client talking to two services generated by this portal must not have to branch on which
    language each was written in.
    """
    with TestClient(create_app()) as client:
        response = client.get("/does-not-exist")

    assert response.status_code == 404
    body = response.json()
    assert set(body) >= {"error", "message", "statusCode"}
    assert body["statusCode"] == 404
