---
to: migrations/script.py.mako
---
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

from collections.abc import Sequence

import sqlalchemy as sa

# Required, and easy to lose. SQLModel renders string columns as
# `sqlmodel.sql.sqltypes.AutoString()`, so an autogenerated migration referencing it fails with a
# NameError at `alembic upgrade` time — after the first statements have already been applied.
import sqlmodel
from alembic import op

${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
