/**
 * Provisioning: generation plus the external side effects.
 *
 * Ordering is the whole design. Everything expensive and failure-prone — validation,
 * rendering, merging, codemods, verification — happens BEFORE the first external call. A
 * generation failure therefore costs only CPU and can be retried freely; only once a complete,
 * verified tree exists do we touch GitHub (doc 06 §1).
 *
 * See docs/plan/06-orchestration-queue-vcs.md §6 for the failure and rollback rules.
 */

import type { ProjectSpec } from '@idp/core';
import type { GenerateResult, VirtualFile } from '@idp/generator';
import {
  DEFAULT_PROTECTION_RULES,
  type ProtectionRules,
  type RepoRef,
  type SecretRef,
  type TeamGrant,
  type VcsDriver,
} from './types.js';

export type ProvisionStage = 'availability' | 'create' | 'push' | 'configure';

export interface ProvisionOptions {
  driver: VcsDriver;
  spec: ProjectSpec;
  /** A verified tree from runPipeline. Provisioning never generates; it only publishes. */
  generated: Pick<GenerateResult, 'files'>;
  commitAuthor?: { name: string; email: string };
  secrets?: readonly SecretRef[];
  protection?: ProtectionRules;
  onStage?: (stage: ProvisionStage, status: 'start' | 'done' | 'fail') => void;
}

export interface ProvisionWarning {
  operation: string;
  message: string;
}

export interface ProvisionResult {
  repo: RepoRef;
  sha: string;
  fileCount: number;
  /**
   * Non-fatal post-push failures. The repository exists and is usable; these are things to
   * retry, not reasons to destroy it.
   */
  warnings: ProvisionWarning[];
}

export class SlugTakenError extends Error {
  constructor(org: string, name: string, reason?: string) {
    super(
      `Cannot create ${org}/${name}: ${reason ?? 'a repository with that name already exists.'}`,
    );
    this.name = 'SlugTakenError';
  }
}

export class ProvisionFailedError extends Error {
  constructor(
    readonly stage: ProvisionStage,
    readonly rolledBack: boolean,
    cause: unknown,
  ) {
    super(
      `Provisioning failed at "${stage}": ${cause instanceof Error ? cause.message : String(cause)}` +
        (rolledBack ? ' (the partially created repository was removed)' : ''),
    );
    this.name = 'ProvisionFailedError';
    this.cause = cause;
  }
}

export async function provision(options: ProvisionOptions): Promise<ProvisionResult> {
  const { driver, spec, generated } = options;
  const stage = options.onStage ?? (() => {});

  const { slug, repo: repoConfig } = spec.meta;
  const org = repoConfig.org;
  const files: readonly VirtualFile[] = generated.files;

  // ── availability ───────────────────────────────────────────────────────────
  stage('availability', 'start');
  const availability = await driver.checkAvailability(org, slug);

  if (availability.status === 'taken') {
    stage('availability', 'fail');
    throw new SlugTakenError(org, slug, availability.reason);
  }
  // `unknown` proceeds deliberately: repo creation is itself atomic and will fail with a
  // conflict if the name is taken. Blocking on a failed lookup would make a GitHub blip
  // indistinguishable from a genuine collision.
  stage('availability', 'done');

  // ── create ─────────────────────────────────────────────────────────────────
  stage('create', 'start');
  let repo: RepoRef;
  try {
    repo = await driver.createRepo({
      org,
      name: slug,
      ...(spec.meta.description ? { description: spec.meta.description } : {}),
      visibility: repoConfig.visibility,
      defaultBranch: repoConfig.defaultBranch,
    });
    stage('create', 'done');
  } catch (cause) {
    stage('create', 'fail');
    throw new ProvisionFailedError('create', false, cause);
  }

  // ── push ───────────────────────────────────────────────────────────────────
  stage('push', 'start');
  let sha: string;
  try {
    sha = await driver.pushTree(repo, files, {
      message: `feat: scaffold ${spec.meta.projectName}\n\nGenerated by the Internal Developer Portal.`,
      authorName: options.commitAuthor?.name ?? 'Internal Developer Portal',
      authorEmail: options.commitAuthor?.email ?? 'idp@users.noreply.github.com',
    });
    stage('push', 'done');
  } catch (cause) {
    stage('push', 'fail');

    // Compensating action. Safe here and ONLY here: we created this repository moments ago in
    // this same job and the push failed, so it contains nothing anyone could have cloned.
    let rolledBack = false;
    try {
      await driver.deleteRepo(repo);
      rolledBack = true;
    } catch {
      // Deletion failing is not worth masking the original error — the push failure is the
      // actionable one, and an empty leftover repo is a minor cleanup.
    }
    throw new ProvisionFailedError('push', rolledBack, cause);
  }

  // ── configure ──────────────────────────────────────────────────────────────
  // Past this point the repository is real, pushed and usable. Failures here are recorded as
  // warnings and NEVER trigger rollback: a working repo missing branch protection is far
  // better than a deleted repo someone has already cloned (doc 06 §6).
  stage('configure', 'start');
  const warnings: ProvisionWarning[] = [];

  const attempt = async (operation: string, fn: () => Promise<void>): Promise<void> => {
    try {
      await fn();
    } catch (cause) {
      warnings.push({
        operation,
        message: cause instanceof Error ? cause.message : String(cause),
      });
    }
  };

  await attempt('setTopics', () => driver.setTopics(repo, topicsFor(spec)));

  if (repoConfig.teamSlugs.length > 0) {
    const teams: TeamGrant[] = repoConfig.teamSlugs.map((teamSlug) => ({
      teamSlug,
      permission: 'push',
    }));
    await attempt('grantTeams', () => driver.grantTeams(repo, teams));
  }

  const secrets = options.secrets ?? [];
  if (secrets.length > 0) {
    await attempt('setSecrets', () => driver.setSecrets(repo, secrets));
  }

  // Last, because protection rules reference status checks that the pushed workflows define,
  // and because GitHub rejects protection on a branch that does not yet exist.
  if (repoConfig.branchProtection) {
    await attempt('protectBranch', () =>
      driver.protectBranch(
        repo,
        repoConfig.defaultBranch,
        options.protection ?? DEFAULT_PROTECTION_RULES,
      ),
    );
  }

  stage('configure', warnings.length > 0 ? 'fail' : 'done');

  return { repo, sha, fileCount: files.length, warnings };
}

/**
 * Repository topics, used to find generated projects later ("every repo we scaffolded for
 * this client", "everything still on Fastify").
 *
 * GitHub rejects the whole call if any single topic is invalid, so each is normalised to
 * lowercase alphanumeric-and-hyphen and empties are dropped — one client named "ACME (UK)"
 * must not cost the repo all of its topics.
 */
export function topicsFor(spec: ProjectSpec): string[] {
  const candidates = [
    'idp-generated',
    `client-${spec.meta.clientName}`,
    spec.meta.deploymentTarget,
    ...(spec.ui ? [spec.ui.framework, spec.ui.styling] : []),
    ...(spec.api ? [spec.api.runtime, spec.api.paradigm] : []),
    ...(spec.api && spec.api.database !== 'none' ? [spec.api.database] : []),
  ];

  const seen = new Set<string>();
  for (const candidate of candidates) {
    const topic = candidate
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);
    if (topic) seen.add(topic);
  }
  // GitHub caps a repository at 20 topics.
  return [...seen].slice(0, 20);
}
