/**
 * README composition.
 *
 * Each recipe contributes the section describing what *it* added, and the finalize stage
 * assembles them. The alternative — one giant README template full of conditionals — becomes
 * unreadable at even a handful of options, and every new recipe would have to edit it.
 *
 * Order comes from each section's explicit `order`, not from recipe execution order, so the
 * reading experience stays sensible (Getting Started before Deployment) even though recipes
 * run in dependency order.
 */

import type { ReadmeSection } from '../types.js';

/** Reserved bands, so recipes can slot in without coordinating. */
export const README_ORDER = {
  intro: 100,
  gettingStarted: 200,
  architecture: 300,
  frontend: 400,
  backend: 500,
  database: 600,
  environment: 700,
  testing: 800,
  deployment: 900,
  operations: 1000,
} as const;

interface SectionContribution {
  recipeId: string;
  section: ReadmeSection;
}

export class ReadmeBuilder {
  readonly #sections: SectionContribution[] = [];

  add(recipeId: string, section: ReadmeSection): void {
    this.#sections.push({ recipeId, section });
  }

  /**
   * Assembles the document.
   *
   * Ties on `order` break on heading, then recipe id — a total ordering, so two runs of the
   * same spec produce byte-identical output (doc 05 §6).
   */
  build(title: string, subtitle?: string): string {
    const ordered = [...this.#sections].sort(
      (a, b) =>
        a.section.order - b.section.order ||
        a.section.heading.localeCompare(b.section.heading) ||
        a.recipeId.localeCompare(b.recipeId),
    );

    const parts: string[] = [`# ${title}`];
    if (subtitle) parts.push('', subtitle);

    for (const { section } of ordered) {
      parts.push('', `## ${section.heading}`, '', section.body.trim());
    }

    parts.push(
      '',
      '---',
      '',
      '_Generated by the Internal Developer Portal. Re-running the wizard with this project’s',
      '_saved spec reproduces this scaffold; local changes are yours to keep._',
    );

    return `${parts.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;
  }
}
